version: '3.7'
services:
    kopia:
        image: kopia/kopia:latest
        hostname: Hostname
        container_name: kopia
        restart: unless-stopped
        networks:
          - proxy
        ports:
            - 51515:51515
        # Setup the server that provides the web gui
        command:
            - server
            - start
            - --disable-csrf-token-checks
            - --insecure
            - --address=0.0.0.0:51515
            - --server-username=${KOPIA_USER}
            - --server-password=${KOPIA_PASSWORD}
        environment:
            # Set repository password
            KOPIA_PASSWORD: CHANGEME
            USER: CHANGEME
        volumes:
            # Mount local folders needed by kopia
            - /srv/docker-data/kopia/config:/app/config
            - /srv/docker-data/kopia/cache:/app/cache
            - /srv/docker-data/kopia/logs:/app/logs
            # Mount local folders to snapshot
            - /srv/docker-data:/data:ro
            # Mount repository location
            - /srv/docker-data/kopia/repo:/repository
            # Mount path for browsing mounted snaphots
            - /srv/docker-data/kopia/tmp:/tmp:shared
        labels:
          - "traefik.enable=true"
          - "traefik.http.routers.kopia-secure.tls=true"
          - "traefik.http.routers.kopia-secure.entrypoints=https"
          - "traefik.http.routers.kopia-secure.rule=Host(`backup.chaosag.website`)"
          - "traefik.http.services.kopia.loadbalancer.server.port=51515"
          - "traefik.docker.network=proxy"
networks:
  proxy:
    external: true